const brands = ["Acura" , "Alfa Romeo" , "Aston Martin" , "Audi" , "Bentley" , "BMW" , "Bugatti" , "Buick" , "Chevrolet" , "Chrysler" , "Citroën" , "Dodge" , "Ferrari" , "Fiat" , "Ford" , "GMC" , "Honda" , "Hyundai" , "Jaguar" , "Jeep" , "Kia" , "Lamborghini" , "Land Rover" , "Lexus" , "Lincoln" , "Lotus" , "Maserati" , "Mazda" , "McLaren" , "Mercedes Benz" , "Mini" , "Mitsubishi" , "Nissan" , "Peugeot" , "Porsche" , "RAM" , "Renault" , "Rolls Royce" , "Subaru" , "Suzuki" , "Tesla" , "Toyota" , "Volkswagen" , "Volvo"];
const models = {
    "Acura":["ILX" , "TSX" , "TL" , "RLX" , "RDX" , "CRV" , "MDX" , "ZDX" ],
    "Alfa Romeo":[ "6" , "6C" , "8C" , "8C Competizione" , "20/30 HP" , "A.L.F.A 24 HP" , "33" , "33 Stradale" , "A.L.F.A 40/60 HP" , "75" , "90" , "145" , "146" , "147" , "155" , "156" , "159" , "164" , "166" , "1750 Berlina" , "1900" , "2000" , "2300" , "2600" , "Alfasud" , "Alfetta" , "Arna" , "Brera" , "G1" , "Giulia" , "Giulia (2015)" , "Giulia GTA" , "Giulietta" , "Giulietta (2010)" , "Giulietta (1977)" , "GT" , "GTA" , "GTV" , "Matta" , "MiTo" , "Montreal" , "RL" , "RM" , "Spider" , "Sprint" , "Stelvio" , "SZ" , "Tonale"],
    "Aston Martin":["DB4" , "DB5" , "DB7 Vantage" , "DB7 Vantage Volante" , "DB9" , "DB9 Volante" , "DBS" , "DBS Volante" , "V8 Vantage" , "V8 Vantage Roadster" , "V12 Vantage" , "Vantage S" , "Vanquish" , "Cygnet" , "Virage" , "Rapide S" , "One-77" , "DBR9" , "V12 GT Zagato"],
    "Audi":["100" , "80" , "50" , "200" , "Quattro" , "90" , "Coupe GT" , "Sport Quattro" , "V8" , "Coupe" , "A6" , "Cabriolet" , "A8" , "A4" , "A3" , "Duo" , "TT Coupe" , "TT Roadster" , "A2" , "Q7" , "A6 Allroad Quattro" , "TT" , "A5" , "Q5" , "TT 2.0 TDI" , "A1" , "A7" , "Q3" , "S2" , "Avant Rs 2" , "S8" , "S6" , "S4" , "S3" , "RS4 Avant" , "RS6" , "TTS" , "E-Tron"],
    "Bentley":["Azure", "Arnage" , "Bentayga" , "Brooklands" , "Continental GT" , "Continental GTC" , "Continental Flying Spur" , "Hunaudieres" , "Mulsanne" , "Silver Wings"],
    "BMW":["3/15","3/20","303","309","315","319","329","501","502","520","600","700","Série 02","1600 GT Glas GT","Série 8 E31","Série 3 E36","Série 3 E46","Z4 E85","Série 1 E87","Série 3 E90","Série 3 Touring Sports Wagon E91","Z4 Coupé E86","Série 3 Coupé E92","Série 3 Conversível E93","Série 5 F10","Série 7 F01","Série 7 Longa F02","Série 3 F30","Série 2 F22","Série 2 F23","Série 2 Active Tourer F45","Série 2 Gran Tourer F46","M1,M2 Série 2","M3 Série 3","M3 GTR E46","M3 E92","M5 Série 5","M6 Série 6","Série 5 E34","Série 5 E28","Série 5 E39","Série 6 E63","Série 6 E64","Série 7 E65","Série 7 E66","Série 7 E67","Série 7 E68","CLR 500 RS Lumma","ACS 4 Sport Coupé","Nazca C2","I8","X1","Concept Gran Coupé","Compact","I3","328","330Cd","E3","E9","Série 5 E12","X6","Z1","Z3","V12 LM","V12 LMR","Hydrogen 7","H2R","Série 3 E21","Série 7 E23","Série 6 E24","Série 3 E30","Z8 E52","X5 E53","X3 E83","X5 E70","X3 F25"],
    "Bugatti":["Type 13", "Type 18", "Type 35", "Royale Type 41","Type 46" , "Type 55" , "Type 57", "Type 101", "Type 252", "Automobili S.p.A", "EB110", "EB112", "EB118", "EB218"],
    "Buick":["Apollo" , "Centurion" , "Lucerne" , "Century" , "Eight" , "Electra" , "Estate Wagon" , "Gran Sport" , "Park Avenue" , "GSX" , "Invicta" , "LeSabre" , "Limited" , "Park Avenue" , "Rainier" , "Reatta", "Regal", "Rendezvous", "Riviera", "Roadmaster", "Royaum", "Skyhawk", "Skylark", "Somerset", "Special", "Sport Wagon", "Super", "Terraza", "Wildcat" , "LaCrosse (E.U.A)", "Allure (Canadá)", "Enclave (E.U.A)", "Excelle (China)", "G-séries (China)", "GL8 (China)", "HRV (China)", "Lucerne (E.U.A)", "Park Avenue (China)", "Royaum (China)", "Sail (China)", "Cascada"],
    "Chevrolet":["150","210","3100","A-10","A-20","Agile","Astra","Astro","Avalanche","Aveo","Bel Air","Beretta","Blazer","Bolt","Bonanza","C-10","Série 10","C-15","C-20","C-1414","C-1416","Calibra","Camaro","Caprice","Captiva","Cavalier","Celebrity","Celta","Chevelle","Chevette","Groove Concept","Sequel","Trax Concept","Tru 140S","Chevy 500","Citation","Citation IV","Classic","Cobalt","Colorado","Corsa","Corsa Pick-up","Corsa Sedan","Corsica","Corvair","Corvette","Corvette C5-R","Corvette C6.R","Cruze","D-10","Série 20","El Camino","Epica","Equinox","Evanda","Express","Fleetline","G2X","Grand Blazer","HHR","Impala","Ipanema","Kadett","Lacetti","Lanos","Lumina","Lumina APV","LUV D-Max","Malibu","Marajó","Meriva","Montana","Monte Carlo","Monza","Monza (Estados Unidos)","Monza (China)","Niva","Nomad","Nova","Nubira","Omega","Omega Suprema","Onix","Opala","Optra","Orlando","Onix Plus","Geo Prizm","Rezzo","S10","Senator","Silverado","Sonic","Spark","Spectrum","Spin","Sprint","SSR","Suburban","Tacuma","Tahoe","Tigra","Tracker","Trailblazer (2012)","Trailblazer (2019)","Traverse","Trax","Uplander","Vectra","Vega","Venture","Veraneio","Vivant","Volt","Zafira","Opel Zafira"],
    "Chrysler":["200","300","300C","300M","Aspen","Avenger","200C","ecoVoyager","Cirrus","Concorde","Conquest","Crossfire","D 50","Delta","Dynasty","Galant","Horizon","Imperial","Imperial Parade Phaeton","Intrepid","Lancer","LeBaron","LHS","Neon","Pacifica","PT Cruiser","Sebring","Sunbeam","Town & Country","Viper","Viper GTS-R","Chrysler Voyager","Chrysler Ypsilon"],
    "Citroën":["2CV","Aircross","Ami","AX","Axel","Berlingo","BX","C1","C3","C3 Aircross","C4","C4 Cactus","C4 Lounge","C4 SpaceTourer","C5","C6","C15","C25","Ami","C-Zero","CX","Dyane","DS","DS5","GS","H Van","Jumper","Jumpy","M35","Méhari","Saxo","SM","Avant","Tipo C","Visa","Xantia","XM","Xsara","Xsara Picasso","ZX"],
    "Dodge":["100","Commando","1800","Aries","Aspen","Atos","Avenger","Bluesmovel","Caliber","Caravan","Challenger","Charger","Conquest","Coronet","D100","Dakota","Dart","Dart PF","Demon Concept","Rampage","Tomahawk","Venom","Zeo","Durango","Dynasty","Fluid Drive","Gran Coupe","Grand Caravan","Intrepid","Journey","Lebaron","Fargo","Magnum","Mini Ram","Neon","Nitro","Omni 024","Polara (Brasil)", "Polara (América do Norte)","Polara (Estados Unidos)","Pickup","Ram 50","Ram STR 10","Spirit","Sprinter","Stratus","Super Bee","Town Wagon", "C","Viper", "Warlock","WC"],
    "Ferrari":["125 S","159 S","166","166 Inter","166 S","195 Inter","195 S","208 GT4","212 Export","212 Inter","250","250 GTE","250 GTO","250 TR 61 Spyder Fantuzzi","275","288 GTO","308 GT4","308 GTB/GTS","308 GTS","328","328 GTB","328 GTS","330","333 SP","348","360","365","365 GT4 BB","400","412","456","458","488 GTB","512BB","550","575M Maranello","599 GTB Fiorano","599 GTO","612 Scaglietti","América","Berlinetta Boxer","California","Daytona","Dino 246 GT/GTS","Enzo Ferrari","F12 Berlinetta","F40","F50","F355","F355 Challenge","F430","158","250 Europa GT","250 GT California Spyder","499P","555 F1","575 Maranello","1512","Purosangue","TR","FF","FXX","GG50","GT4","LaFerrari","Mondial","P4/5 by Pininfarina","SF90 Stradale","Testarossa"],
    "Fiat": ["1","4 HP","6 HP","8 HP","10 HP","12 HP","70","124","125","126","127","128","130","131","132","147","242","500","500L","500X","600","850","1100","1300","1400","1900","1500","1800","2100","2000","2300","Albea","Argenta","Argo","Barchetta","Brava","Bravo","C8","Campagnola","Cinquecento","City","Coupé","Croma","Cronos","Daily","Dino","Doblò","Ducato","Titano","Duna","Elba","60 HP","Fastback","Pulse","Fiorino","Freemont","Grand Siena","Grande Punto","Idea","L3","35","Linea","Marea","Marea Weekend","Marengo","Mio","Mobi","Multipla","Nuova Panda","Oggi","Ottimo","Palio","Palio Elétrico","Phylla","Palio Weekend","Panda","Panorama","Prêmio","Punto","Regata","Ritmo","Scudo","Sedici","Seicento","Siena","Stilo","Strada","Tempra","Tipo","Topolino","Toro","Ulysse","Uno","Viaggio","Weekend","X1/9","Zero"],
    "Ford":["7Y","1941","Activa","Aerostar","Anglia","Aspire","Bantam","Belina","Bronco","Bronco II","Bronco Sport","C-Max","CMaxEnergi","Capri","Comuta","Consul","Contour","Corcel","Corsair","Cortina","Cougar","Country Squire","Courier","Crown Victoria","Crown Victoria Police Interceptor","CX","Del Rey","E-Series","Econoline","Econovan","EcoSport","Edge","Eifel","Elite","Escape","Escort (Brasil)","Escort (Europa)","Escort (América do Norte)","Escort (China)","Everest","Excursion","EXP","Expedition","Explorer","F-250","F-1000","F-Series","Fairlane (América do Norte)","Fairlane (Austrália)","Falcon","Falcon (América do Norte)","Falcon (Argentina)","Falcon (Austrália)","Festiva","Fiesta","Fiesta Mark 3","Five Hundred","Focus","Focus RS WRC","F-75","Model Y","Forty-Nine","Freestar","Freestyle","Fusion","Fusion Hybrid","Futura","Galaxie","Galaxy","Granada (América do Norte)","Granada (Europa)","GT","GT40","GT90","Ikon","Indigo","Ka","Köln","Kuga","Laser","LTD (América do Norte)","LTD (Austrália)","LTD Crown Victoria","Mainline","Maverick","Maverick (2021)","Meteor","Model 48","Model A","Model A (1903)","Model A (1927)","Model B (1904)","Model C","Model F","Model K","Model N","Model R","Model S","Model T","Model U","Mondeo","Mustang","Mustang Mach-E","Mustang Shelby GT500","Nucleon","Orion","Pampa","Parklane","Pilot","Pinto","Popular","Prefect","Probe","Puma","Ranch Wagon","Ranchero","Ranger","Rheinland","Royale","Willys","S-MAX","Scorpio","Shelby GR-1","Sierra","Squire","Taunus","Taurus","Taurus (2008)","Taurus X","Telstar","Tempo","Territory","TH!NK","Thunderbird","Torino","Transit","Transit Connect","Vedette","Verona","Versailles","Verve Concept","Windstar","Zephyr"],
    "Honda": ["1300","Accord","Capa","City","City Turbo","Civic","CR-V","CR-X","CR-Z","Crosstour","Fit","Freed","HR-V","Insight","Legend","Life Dunk","Logo","Mobilio","Honda H","NSX","Passport","S500","Stream","Vezel","WR-V","Zest","ZR-V"],
    "GMC":["Acadia","Canyon","Denali XT Hybrid Concept","Envoy","Old-Look","K5 Jimmy","S-15 Jimmy","Sierra","Sonoma","Syclone","Terrain","Topkick","Typhoon","Yukon","Yukon XL"],
    "Hyundai":["Accent","Atos","Atos Prime","Azera","BlueOn","Creta","Dynasty","Elantra","Entourage","Eon","Equus","Excel","Galloper","Genesis","Genesis Concept","Genesis Coupe","Getz","H100","HB20","HB20S","HED-5","HR","i10","i20","i30","i40","i800","ix20","ix35","ix55","Kauai","Kona","Lafesta","Matrix","Nuvis","Pony","QarmaQ Concept","S-Coupe","S-Coupé","Scoupe","Santa Cruz","Santa Fe","Santamo","Sonata","Starex","Stellar","Terracan","Tiburon","Trajet","Tucson","Veloster","Veracruz"],
    "Jaguar":["SS 1","Jaguar 420","C-X75","C-XF","E-Type","F-Pace","F-Type SVR","I-Pace","Mark 1","Mark 2","Mark IV",
    "Mark IX","Mark V","Mark VII","Mark VIII","Mark X","S-Type (1963)","S-Type (1999)","X-Type","XE","XF","XJ","XJ220","XJR-9","XJR-12","XJR-14","XJS","XK","XK120"],
    "Jeep":["Avenger","Cherokee (KL)","Cherokee (XJ)","Comanche","Commander (XK)","Commander (2021)","Compass","Grand Cherokee","Willys Jeep Station Wagon","Willys Jeep Truck","Willys-Overland Jeepster","Jeepster Commando","Liberty","Patriot","Renegade","Trailhawk","Wagoneer","Wrangler"],
    "Kia":["Amanti","Avella","Besta","Bongo","Borrego","Brisa","Cadenza","Carens","Carnival","Cee'd","Cerato","Clarus","Credos","Elan","Forte","Grand Carnival","K9","K2500","KND-4 Concept","KOUP Concept","Kue","Lotze","Magentis","Mentor","Mohave","Morning","Opirus","Optima-Regal","Picanto","Pop","Pride","Pro-cee'd","Quoris","Rio","Rio Cinco","Sedona","Sephia","Sorento","Soul","Soul'ster","Spectra","Sportage","Stonic","Venga","Visto"],
    "Lamborghini": ["350 GT","400 GT","Athon","Aventador","Bravo","Calà","Countach","Diablo","Espada","Estoque","Faena","Gallardo","Huracán","Islero","Jalpa","Jarama","Marzal","Murciélago LP640","Sián","LM002","Marco Polo","Miura","Murciélago","Reventón","Sesto Elemento","Silhouette","Urraco","Urus","Veneno"],
    "Land Rover":["101 Forward Control","Defender","Discovery","Discovery Sport","Freelander","LRX","Range Rover","Range Rover Autobiography","Range Rover Classic","Range Rover Evoque","Range Rover Sport","Série 1","Wolf"],
    "Lexus":["CT","ES","GS","GX","HS","HS 250h","IS","IS-F","LF","LS","LX","RX","RX 400h","SC"],
    "Lincoln": ["Aviator","Blackwood","Capri","Continental","Cosmopolitan","K","Town Car","LS","Mark","Mark LT","MKR","MKS","MKX","MKZ","Navigator","Premiere","Versailles","Zephyr"],
    "Lotus":["Carlton","Elan","Elise","Elise GT1","Elite","Esprit","Europa","Europa S","Evora","Exige","Mark I","Wet Nellie"],
    "Maserati":["8CTF","3200 GT","3500","A6","A6GCM","Coupé","Ghibli","GranCabrio","GranTurismo","Levante","Biturbo","Quattroporte"],
    "Mazda":["2","3","121","323F","626","717C","727C","737C","757","767B","787B","929","929 Coupe","1800","Atenza","AZ-Offroad","B-Series","B360","B600","Biante","Bongo","BT-50","Capella","Carol","Cosmo","Cronos","CX-5","CX-7","CX-9","Demio","Familia","Furai Concept","Hakaze","Kabura","Kazamai","Kiyora Concept","Lantis","Laputa","Mazda5","Mazdago","Miata","Millenia","MPV","MX-3","MX-5","MX-6","MXR-01","Nagare","Navajo","Persona","Porter","Premacy","R100","R360","Revue","Roadpacer","RX-2","RX-3","RX-4","RX-5","RX-7","RX-8","RX-792P","Ryuga","Scrum","Sentia","Shinari Concept","Speed6","Spiano","Titan","Verisa","Xedos","Xedos 6"],
    "McLaren":["F1","Senna","MP4-12C","P1","SLR McLaren"],
    "Mercedes Benz":["600","Actros","AGF Serval","AMG","Atego","C292","Citaro","Classe CLA","Classe A","Classe B","Classe C","Classe CL","Classe CLC","Classe CLK","Classe CLS","Classe E","Classe G","Classe GLS","Classe GLA","Classe GLB","Classe GLC","Classe GLK","Classe GLE","Classe R","Classe S","Classe SL","Classe SLC","Classe SLK","Classe V","Classe X","CLK-LM","CLR","CLS","F700","FSK","L3000","300 SL","300 SLR","C111","EQS SUV","W25","NAFA","O-370","O-371","O-400","O-500","O-305","Sauber C9","SLR McLaren","Sprinter","Unimog","Vision A 93","Vito","W15","W111"],
    "Mini":["Clubman","Cooper","Cooper Convertible","Cooper S","Cooper S Convertible","Countryman","One","One Convertible","One D","Rocketman"],
    "Mitsubishi":["360","500","3000GT","Airtrek","Aspire","ASX","Carisma","Celeste","Challenger","Chariot","Colt","Colt 600","Colt Galant","Concept CX","Delica D5","Diamante","Eclipse","Eclipse Cross","FTO","Galant","randis","i","i-MiEV","L200","Lancer","Lancer Evolution","Magna","Minica","Galloper","Mirage","Mizushima","Model A","Outlander","Pajero","Pajero Pinin","Pajero Sport","PX33","Raider","RVR","Sigma","Space Cargo","Space Star","Space Wagon","Starion","Strada","Strakar","Triton"],
    "Nissan":["100NX","180SX","200SX","240SX","280ZX","300ZX","350Z","370Z","810","Actic","Almera","Altima","Altra","Armada","Atlas","Avenir","Axxess","Azeal","Bakkie","Be-1","Bevel","Bluebird","Caravan","Cedric","Cefiro","Cherry","Cima","Crew","Cube","D21","Elgrand","Figaro","Foria","FORUM","Frontier","Gazelle","Gloria","Grand Livina","GT-R","GT-R LM Nismo","Hypermini","Jonga","Juke","Kicks","Lafesta","Largo","Laurel","Leaf","Liberty","Livina","Livina Geniss","March","Maxima","Micra","Mistral","Mixim","Murano","Rasheen","Note","Nuvu","NV200","Nissan NV2500","P35","Paladin","Pao","Pathfinder","Patrol","Pintara","Pivo","Pixo","Prairie","Presage","Presea","President","Primastar","Primera","Pulsar","Qashqai","Qashqai+2","Qazana","R.D:B.X","R'nessa","R380","R381","R382","R383","R390","R390 GT1","R391","Rogue","Sentra","Serena","Silvia","Skyline","Skyline GT-R","Skyline GTR R34","Stanza","Sunny","Sylphy","Teana","Terra","Tiida","Titan","Tone","Townpod","Tsuru","URGE","Ute","Vanette","Latio","Versa","Versa Note","Wingroad","X-Trail","Xterra","Z-car"],
    "Peugeot":["5CV","104","106","107","201","202","203","204","205","206","206 Escapade","207","207 Brasil","207 SW","207 SW Outdoor","208","304","305","306","307","307 WRC","308","308 Hybride HDi","308 SW Prologue","309","403","404","405","406","407","408","504","505","508","604","605","607","806","807","905","907","908 HDi FAP","908 RC","1007","2008","3008","4007","4008","5008","BB1","Bébé","Bipper","Flux","Hoggar","Moovie","P4","Partner","9X8","Oxia","Quasar","Quadrilette","RCZ","Tipo 1","Tipo 2","Tipo 3","Tipo 4","Tipo 5","Tipo 6","Tipo 190"],
    "Porsche":["911","911 GT1","914","917","918","919 Hybrid","924","928","930","935","936","944","953","959","961","962","964","968","991","993","996","997","Boxster","Carrera","Carrera GT","Cayenne","Cayman","Dauer 962 Le Mans","Macan","Mission E","P1","Panamera","356","989","992","Taycan","RS Spyder","WSC-95"],
    "RAM":["RAM 1500","RAM 2500","RAM 3500","RAM Classic","RAM Rampage"],
    "Renault":["Renault 3","4CV","4L","5","6","7","8","9","10","11","12","14","15","17","16","18","19","20","30","21","25","Alpine A108","Alpine A110","Alpine A310","Alpine A610","Alaskan","Arkana","Avantime","Berliet Tramagal","Captur","Caravelle","Celtaquatre","Clio","Clio Grandtour Concept","Colorale","Dauphine","DeZir","Dacia Duster","Duster","Oroch","Samsung EMX","Espace","Express","Fluence","Frégate","Fuego","Grand Scénic","Joaninha","Juvaquatre","Kadjar","Kangoo","Kardian","Koleos","Kwid","Laguna","Latitude","Logan","Dacia Logan MCV","Magnum","Master","Mégane","Modus","Motrio","Nepta","Ondelios","Primaquatre","Samsung QM5","Samsung QM5 SUV","Samsung QMX","Racoon","KJ","Monaquatre","Monasix","MT","NN","R35","Rodeo","Safrane","Sand Up","Sandero","Scala","Scénic","Scénic ZEV H2","Sherpa Light","Samsung SM3","Samsung SM5","Samsung SM7","Dacia Solenza","Spider","Symbol","Talisman","Táxis do Marne","IKA-Renault Torino","Trafic","Twingo","Twizy","Vel Satis","Voiturette","Wind","Z.E","Zoe"],
    "Rolls Royce":["10 hp","15 hp","20 hp","30 hp","Legalimit","Silver Ghost","40 hp","50 hp", "Phantom","25 hp","Phantom II","Phantom III","Wraith","Silver Wraith","Silver Dawn","Phantom IV","Silver Cloud","Phantom V","Phantom VI","Silver Shadow","Ghost","Series II","Cullinan"],
    "Subaru":["360","Alcyone SVX","Ascent","Baja","Bighorn","BRZ","Exiga","Forester","G3X Justy","G4e","Impreza","Impreza Design Concept","Impreza WRC","Justy","Legacy","Outback","Pleo","R-2","R1","R2","Rex","Stella","Sambar","Traviq","Trezia","Tribeca","Vivio","WRX","XT","XV"],
    "Suzuki":["Alto","Cappuccino","Carry","Forenza","Hustler","Ignis","Jimny","Reno","SX4","SX4 WRC","Vitara"],
    "Tesla":["Model 3","Model Y","Model X","Model S Plaid","Cybertruck","Model S Shotting Brake","Roadster MKL","Roadster MKLL"],
    "Toyota":["4Runner","86","88C","88C-V","A-BAT","AE86","Allion","Alphard","Altezza","Aristo","Aurion","Auris","Auris Touring Sports","Avalon","Avensis","Aygo","Bandeirante","Belta","C-HR","Camry","Celica","Celsior","Century","Chaser","Corolla","Corolla Levin","Corona","Cressida","Crown","Cynos","Dyna","Estima","Etios","FCHV","Fielder","FJ Cruiser","GT-One","Hiace","Highlander","Hilux","Hilux SW4","Hybrid-X Concept","IQ","Isis","Ist","Kluger","Land Cruiser","Lexcen","Mark X Zio","MR2","Opa","Paseo","Passo","Picnic","Pod","Previa","Prius","Prius V","Prius c","Prius Plug-In Hybrid","Ractis","RAV4","Sequoia","Sienna","Sprinter Trueno","Stout","Supra","Tacoma","Tarago","2000GT","Cross","GR010 Hybrid","HiAce","Sera","TS030","TS040","TS050","Tundra","Urban Cruiser","Vellfire","Venza","Verso","Vitz","Wish","Yaris"],
    "Volkswagen":["181","183","1600","Amarok","Apollo","Arteon","Atlas","Bora","Bora (China)","Brasília","Bus","Caddy","Caravelle","CC","City Golf","Corrado","Crafter","Cross Fox","Cross Golf","Derby","E-Up","Eos","Eurovan","Fox","Fusca","Fusca (A5)","Go","Gol","Golf","Golf Blue-e-Motion","Golf MK1","Golf Mk3","Golf Variant","ID.4","ID.6","ID.7","IN","Iroc","Jetta","Jetta Variant","K 70","Karmann-Ghia","Karmann-Ghia TC","Kombi","L1","Lavida","Logus","LT","Lupo","Microbus","Milano Taxi","New Beetle","Nivus","Parati","Passat","Passat (B1)","Passat CC","Passat Variant","Phaeton","Plattenwagen","Pointer","Polo","Polo Classic","Polo G40","Polo R WRC","Routan","Safari","Santana","Santana Quantum","Saveiro","Schwimmwagen","Scirocco","Sharan","SP1","SP2","SpaceCross","SpaceFox","T-Cross","T-Roc","Taro","Taro II","Tex","Thing","Taigun","Tiguan","TL","Touareg","Touran","Transporter","Trekker","Typ 3","Typ 4","Type 147","Up","Vanagon","Variant II","Virtus","1-litre concept","BlueSport","Chico","Concept A","EcoRacer","GX3","ID.3","Taos","Up Concept","W12","Voyage","XL1"],
    "Volvo":["200","440","460","700","850","900","Amazon","C30","Duett","ECC","PV 36 Carioca","PV444","PV544","S60","S70","V40","V70","XC40","XC60","XC90"],    
};
const colors = ["Branco", "Preto", "Prata", "Vermelho", "Azul", "Cinza", "Verde"];

// Populate brands
const brandSelect = document.getElementById('brand');
brands.forEach(brand => {
    let option = document.createElement('option');
    option.value = brand;
    option.text = brand;
    brandSelect.add(option);
});

// Populate colors
const colorSelect = document.getElementById('color');
colors.forEach(color => {
    let option = document.createElement('option');
    option.value = color;
    option.text = color;
    colorSelect.add(option);
});

// Update models based on selected brand
function updateModels() {
    const modelSelect = document.getElementById('model');
    const selectedBrand = brandSelect.value;
    modelSelect.innerHTML = '<option value="">Selecione um modelo</option>';
    if (selectedBrand && models[selectedBrand]) {
        models[selectedBrand].forEach(model => {
            let option = document.createElement('option');
            option.value = model;
            option.text = model;
            modelSelect.add(option);
        });
    }
}